# Site settings
title: ChatGPTBookProject
description: A small and silly experiment using ChatGPT to generate a "book" on education and artificial intelligence, curated by me.
avatar: https://raw.githubusercontent.com/franklinwillemen/ChatGPTBookProject/master/images/botwritesbook.PNG
url: https://siliconshakespeare.com
baseurl: "/ChatGPTBookProject"

# Build settings
theme: jekyll-theme-cayman
plugins:
  - jekyll-sitemap
  - jekyll-feed

# Markdown settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'

# Sass settings
sass:
  sass_dir: _sass
  style: compressed

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
